### ISSUE TITLE
java.lang.IllegalArgumentException: Multiple entries with same key:

### ISSUE THREAD

**Issue by ghost** [kyau/afterhours#1]
crash-log see: http://paste.ee/p/KXjSg

The Game freezes if i started my world
Can you fix that.
I Iike your mod a lot

**Comment by setycz** [comment]
Hi there @kyau . I have no problem if you inspire yourself with my mod (Another Dusts), but change QuantumStabilizerRecipeCategory UID at least ;].

**Comment by ghost** [comment]
If I could, I would have done that.
Therefore, I have eliminated the problem in the way that is possible for me at the time.
I wish you a peaceful time

**Comment by setycz** [comment]
Don't close the issue @jokish363 . My comment was for @kyau not for you ;]. @jokish363 , reopen the issue so @kyau can fix that ;].

**Comment by kyau** [comment]
Yea it was used for inspiration on how to do JEI integration and was changed in the next version, thanks for the heads up tho and the great code to learn by! ^^
