### ISSUE TITLE
Crash on joining server

### ISSUE THREAD

**Issue by drewbit** [kyau/afterhours#5]
Using afterhours_1.8.9-0.26.4-66

Crashes when I try to join server, here's the log:
http://paste.ee/p/NUfv6

**Comment by kyau** [comment]
Looks like an issue with when the authentication servers are down or if one is using an offline instance, I pushed a fix for this to Github/CurseForge just now, let me know if it solves the problem.

**Comment by drewbit** [comment]
Just tried it, didn't seem to work. Here's the log again if you want.

http://paste.ee/p/Ai9cH

**Comment by kyau** [comment]
If possible could you try the following test build and see if it fixes the problem?

[afterhours_1.8.9-0.26.4-68](https://kyau.net/afterhours/afterhours_1.8.9-0.26.4-68.jar)

**Comment by drewbit** [comment]
That version gives the same error unfortunately. Here's the log again:

http://paste.ee/p/iqLiB

**Comment by kyau** [comment]
Sorry, having a really hard time replicating the error on my end... I am hoping this fixes it, if not I will have to look at it in the morning.

[afterhours_1.8.9-0.26.4-69](https://kyau.net/afterhours/afterhours_1.8.9-0.26.4-69.jar)

**Comment by drewbit** [comment]
Sorry for the late reply. But this version seems to have fixed the problem, thanks!

**Comment by kyau** [comment]
Cheers, good to know sorry for the issues!
